services:
  pipeline:
    build: .
    container_name: bit-by-bit-pipeline
    runtime: nvidia  # Enable GPU access
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_HOST=0.0.0.0
    ports:
      - "11434:11434"  # Ollama port
    volumes:
      - ./data:/app/data  # Mount data directory
      - ./config:/app/config  # Mount config directory
      - ./logs:/app/logs  # Mount logs directory
    command: ["--step", "all", "--verbose"]  # Run full pipeline with verbose logging
    restart: unless-stopped
